""" Added unique constraints on phone column
    Also added db relationships between artist/venue and show

Revision ID: 9389b4062121
Revises: a32b4658e40c
Create Date: 2022-08-29 00:33:31.096802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9389b4062121'
down_revision = 'a32b4658e40c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artist', ['phone'])
    op.create_unique_constraint(None, 'venue', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='unique')
    op.drop_constraint(None, 'artist', type_='unique')
    # ### end Alembic commands ###
